version: '3'

services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./report.html:/var/www/html/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/monitor.usegalaxy.it/fullchain.pem:/root/ssl/cert.pem
      - /etc/letsencrypt/live/monitor.usegalaxy.it/privkey.pem:/root/ssl/key.pem
