---
version: "3"
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - URL=laniakea-dashboard.cloud.ba.infn.it
      - VALIDATION=http
      - email=***REMOVED***
      - DHLEVEL=2048 #optional
      - ONLY_SUBDOMAINS=false #optional
      - STAGING=false #optional
    volumes:
      - /etc/proxy/config:/config
    ports:
      - 443:443
      - 80:80 #optional
      - "8443:8443"
    restart: unless-stopped
