# MANAGED BY saber #
gAAAAABoEyN7C0UmVTPsPfZD6cQSCWj4iOHmVwLYqFS8GrF4KU-isKQ-uAGA7fFBLIQ2LnUk9wLR8ciN
mOsyXsKLEXYOBEdJSX7pvmonAe4kP0evKGcpTE2LStKScqer0MZNdyN_25tvrc4d7OIjJ22E8pTR17Ow
yHiG_YUUZXQlwdXFaf7gXu0RMyDPnNtuSRyeyD8GiB-6-Msnh1mr8vwk1CMUC3Frsvp-bSE1QESzl3t5
TyAJ6sQS5bOx9FI5see0Oy9l2dkw5uZrZ2DPTZZ27DR9PpwFf0wKgGufx8WKVnJteNugR4lmqxyz8Xc3
f0Aw-RScK607BW2A2aU6ZikEKummvV59meP7QTOpPmQ6TBkTW720iqk-6sK3q3VxS4i0PiY00SGCB4JZ
dkPo8SF-t9IjgY0RdrDJqinS9zwEvxzE9hP2kURlsjtVDs61DgGiDI1uqQ6NcpiHSsqZh0j5bHi3LZpI
T6cViHzEfsQxrRE10jtsyQ9KRPncLMKlZC-5R6cyWO7GZTQsHavY5by3wOFazU5gvPcPAjI899qwbyBO
fTGWafAdRFkLJnQ45a1iDDUG-bjkSLa52f3uNTH2g1UKTR1B-Przb4ikk7onhRxuL3F4AVB7v_bi_9pf
un-3MdTcRbXrLh4Odx4smSw9TG-By5kya77C1rhyeWse5oqt9ondDErylXxblNxB6Ncx706_xfQlMqm0
3bgLOd8hneNH8x5nqQ9dJV180RfqDwWt93WI1jGi2HcYSrV1vHnVxHawpZcBVGvpvLJSMv5DzJf5ibdi
noe0aGnekRvlPOMnT1lTaEcEIHKTFBi3RZ41fARaxc7ixyEd9DXUAmwnYGZM4pVApZY8Is9NtGZeEKY4
DDUiSFsTVtxwtVknYfB2hu9mYsMjLRp3VRyNcYzT6OAff8pzmAqb7IEnu1cz9Tbvm-4xnBWyVlDbzSVM
xPVwBjNAQVNTSOkvi1tpe8PFEUZyCqAkl54P0NS-9RruI4YsXIvNYu7DS0wx31bEt5qRT8rxvfHKBiKE
N7_QLMJ5F7McjtLeu0PAhcbBL1J9QerJ-n4glZ_OHeL3FZXmkeBZa0XIwBNRuwtRnBIR2JnC3nayMUH2
QRQoOUyFMqvyFfGL4W33HIk2W_RmVi48E951_5PSs3TKKNKR25CmrSKeh1ieGvAKp8PnXKxmOlIPyIi0
b9MHfOX0zGVlgWV8MNBcNBbCgTK6g3ulzYCgl8ThsCv_C7bmJ1qc0D1gDdfGfeNXcEXr0w3LxzuG9YLt
i10v11RZ9qb-_r_3QpHS5EVgOEtJPY7qHjHcWaig3QIZAOGs4zC8CilxF8qoCKDd1Hf-w0PQdN5AKEyw
_PRwp94cJkDQa7q1ecsnR0Fh5bsbuSsyY2cJNSaN1T26_zXPz6ybGtnnNH31-2Iz4d8wnvKeqBN6quTW
rqeTtTfaDRJhVeTh330z1149j8pJCRTnZ9-qCIMZFwcW32FMfVCVpP961O6pbXUJolFm4k0IZRURwc4U
BGlHeUCVtteOxQ3Pktqq6KhcLRoW4PU9Q_sEcd5TdNp5kxP-_fT028jZJoB7b6Fwg9D743OXjyb1B89X
SMEMymxfGQxn
