# MANAGED BY saber #
gAAAAABn6nNq2SCw_vpgoEnKnTqrQgdcgmyZcci0qu5xTdzz-LusKGuCQwhiZ99N6fWKzz7K_DGqQCiq
OA9OU9jtEj0f8RVMLlXgeiYZ3qZrDeC_tmDSGLP6FraQ-3ML87RDLH39Q3IEN1SkCNr70H7eZ9PpPfTF
7pbGgwB86z-7fKBUDpCtkWFNELUIKRjDE5u2j8e_UNOYXsc16HVd40j9clU-4nUyFn2zj4Rtu7NDvqI9
Zxbg71hHGA_WHhQLcz7KhJVME_53NvfP8IC9CErIt2wu4rnfbOQfSA9qS2UjhUXoBv-6ssN4BaOYcGvS
K0DYJBZdvGwOhgqSYavcCdZ7OQM8IAG57sF9rPuO6ru8Neo3xGUuCj1Ee4P1Hn-aKUFfaS3-urqAOReJ
7VAJY49kb-kqFjMoXOA8GuBkPLhkh2UN7Nk6G2SF-yibrDBQ5rh4V6F-S9Tzc-4yER4_bLQGF6KiYfRQ
6wNy4S5elZVSkJyJcQFDfAm2J9moGNGFUx09ST9t0s5z53H__obPPf7mHiux1H5VvJ_J7lU3nxh0pJv9
nvTHCNy6ujmcS3V1UFX71wvRlHOu3XwnJ3Jc68avz9hIRrdAYCobH8aYcC36CrHsyPMCs5_8hiCsCaiA
K2t_AmH5QnzOvoBVumHS8UoWEUCjv8-PjnE-4v3gZ6QbREkHnkFQEbr_oxWctUKDuRE07lB07uuAVXC5
ZoKnw_ZC2gl8OxkBc3Mo61diGShL1ZFITKFbQpkh8-2iFH5aVw4yn3Wv4gnkuLWK_RU4z9cRX08cJU0I
8UVu4sTGsUbe5v98AmNzZ8PkwAXB3_5p4XazEbxOAJY783aflPZ88AH8ohfIHLUWPZYzo9wnK_TkOa5x
KsumgvzHwDATgT1KnfgjLWMblqD3MoIBxU3EyCizVsxZrH2Vq1L4d34e1COPKsDp5ChXzkjBdJuoMBn8
i17rAiOD8OxX4efmzDHMln7KvWtV0vK9LbSmOs0eefTSP0b1vhrKA4zxUBh2upQwj5WoDRHfcDJ5qpBN
CD7IDrg9prkJRBj6ZBU-M-qyUVGVVcdR6e0F0_JDYEU0YYHMccjIWKtIy7pEjo7BgHQS6h_1d5G0liQE
LCwIC3cqjzD2TQmMLbz2CRl2ht86cjLyeAYQFBVhYh2LMqskdRJUV88KdcOqFR44ZLQEYYwwHtTqjsOy
xc8F0oSCKc_FFoWSTlnWdL87sJ6Zg0nH3D627jqi0E7ZMx85WGLd3YRUQrWhfKm7CYiC8ijgiYnEDtbN
Rrtt6IOtFx7Ox80_q16gf-ELGR3CxtQw66wr3xtwfCHWTPwnqRSWdOpDz9Ql3GfxbyE_vyJwGIxag1Ui
Ubjj_-CfALU-MqHIyKN5S8XhosbI_FamCDxXGon0hoC47cc9bdgqnWqTF_oWnHBiL6_zY6Jbu-OmwmTd
9GfJKaF7v-XOIpHgvoEQRB52GWc0PkNJ5n23y9EMqH9nk73eeGJkRRUoZ8jK9hZ1K0VItzBMa0Q-WIiH
L_uuwsrvKMjYMfX-9L7u2zs3MtRs6zP-SbBeeJdFXeMmm3ZF8g==
