# MANAGED BY saber #
gAAAAABoXmlQ2kDSYk024Xtu49OlCsCHu9JYexRWoUKSD7HqKXH_1lQUDPpj8JMqRh1eVJIcxvzUmckJ
qaQYwxOw45nK0LXTQ3z3gGOT_BQaCPbvXmZ3liuLQNyXk4B2s5O5NkGqAfMw01CIAaOj_uCbeRC0iVc_
oOj82VNiQc_IhHzQK5ygf_wnK6ibzSy2DKqiCutJbxsxyNg9EbSXfOveVixHilrGSLJT-Z0kka3uYUlI
M4yPXDhn2w5dkPhZrl5-0mDOi6GyWkkOP4wSZQNcIjve4pd9idWh6AGSldOZlfzdnLY4AEgGo0A_lflx
z1YKT9AWbEXHrdN4D73BjLRl8O0kWvUsKSaSDnmIMD5md50aremC7RRSou4O4riUYBHYEAQOEONHpy9B
ahhC763lvK05YjcbsJh9T5-VTcHBCsUMGU1QxURYo8Z_BdMXB9HlbDUfDY82zgndehxG0Vq_hlbMCtKp
YfwR0_MsV0bVxBPDn1xjh0Dvt9UINOSbEWefRSC_Bi6SZNIkryLM6_jg-iJ9q6LfJuKUKgPf8iPByiXc
9JliAXPGopmN1xWuX9Fsy4E_s19G9aoemWvJ6MtbQjw6Jr3fGJcki0L1QGIG0KkTJKcGIFsFTRNdeOP-
0nqnHm24DQI1EzVJCELQseF10sQusDYsnvohJMyoPbMRNZwUUdQV7bnCctilFoDF5dvzOgEa8n7fn0Jf
_9Jb-RFzaH-hsWSPfdvAnIka8wup7L9gj5bVEsVaa4LkzQac5taGIhCGU9JGMMTR5kEEZYZU2vQZvoex
W9SxdEyEe73b1moqvxdjnAjcSaJbEsANGXwRO4ZXrd6Y89_QOLW0RJ29CWb8rBA0IowtPVzlf-L_jJmm
7GdNy71Fl-pa2_HUCKznH-LtAWzX1V6om4V8s1TLGdhjHLWguABc-_S3Plmjn7HqDv_9nFTDceLi5YJo
QiTVKs4I5nFHL4Hz4vcKgivlcOnUzAgEDsamRP1UMRrhTUhMu-6MNfgnRJw1X_MbuO_Mo63epQ7Mzd7L
zXsJppbNYWGTAqTztWUE4F0EnhOOUxgaSvLwzQ1QfJN_mtr7s_W-lDGI5890sTeklW_TLepl78ptf8_t
78gfwAqr19n3QB1epYeAzpZ14LQzyAtshoXaiIFF25k_eI8nSQbil_IInWDtUq4gOfhrdXvIbQfutgRj
tVSCvNSU_WVSZss6dTHItqGJ7b9PuhuslioDEHSPQf2lcThjIxT5Z7Osc7pvSdu_GSMkqwnxXSHVuelA
kAXzrpcHAsUy0JngSSM8RpHOObhAIyd5b3xcAQrcw7iPWU4im7hetFWlIdcyZT3P5_eN4Zt6KTgbPcRZ
VMQzVNeCTjfncmq9W4hzAjWtISxvcuSe71hslbzjFaFvpy66JamTDwWs-q2cWscvvRaYdEFdQND25zFP
hK2xlDiDAlfpH4IR95en1YRKbq0URGbchwzGTnkpxfX-OmvLSzeDFcG-8WW0NiQ1O87GloC451ggFbo5
WW4IYadAGorrTOnkR3gO1O938nRLrhYopRaR_mTu_Dve0rUGCk6K6xKGfLkALz04_r_AZpNs-V-7E8iG
1v5hucXsbQiq
